name: Add tag on release EXE

on:
  push:
    branches:
      - main

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Push Pull Request Filter
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - 'exe_packages/**'

    - name: Create tag
      if: steps.changes.outputs.src == 'true'
      env:
        TAG_TOKEN: ${{ secrets.TAG_TOKEN }}
      run: |
        git tag "release/v$(date + '%Y.%m.%d')"
        git push --tags https://oauth2:${TAG_TOKEN}@github.com/polnikov/recalculation-smoke-exhaust-fan.git
