name: Build and Release EXE version

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build app
        run: pyinstaller app_one_file.spec

      - name: Move app to exe_packages directory
        run: |
          mkdir -p exe_packages
          mv home/runner/work/recalculation-smoke-exhaust-fan/recalculation-smoke-exhaust-fan/dist/recalculation-smoke-exhaust-fan/recalculation-smoke-exhaust-fan.exe exe_packages/recalculation-smoke-exhaust-fan_$(date +'%Y.%m.%d').exe
      
      - name: Upload exe to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.ref }}/assets{?name,label}
          asset_path: ./exe_packages/recalculation-smoke-exhaust-fan_$(date +'%Y.%m.%d').exe
          asset_name: recalculation-smoke-exhaust-fan_$(date +'%Y.%m.%d').exe
          asset_content_type: application/x-msdownload

      - name: Create tag
        if: success()
        run: |
          git tag "release $(date +'%Y.%m.%d')"
          git push --tags
