name: Release publication

on:
  push:
    branches:
      - main

jobs:
  creating-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check changes
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'exe_packages/**'

      - name: Create Tag
        if: steps.check_changes.outputs.src == 'true'
        id: create_tag
        env:
          TAG_TOKEN: ${{ secrets.TAG_TOKEN }}
        run: |
          git tag ${{ env.TAG_NAME }}
          git push --tags https://oauth2:${TAG_TOKEN}@github.com/polnikov/recalculation-smoke-exhaust-fan.git
          echo "TAG_NAME=$(v$(date +'%Y.%m.%d'))" >> $GITHUB_ENV
      - name: Check tag name
        run: |
          echo "Calling var from env using env context: ${{ env.TAG_NAME }}"
          echo "Calling var from env: $TAG_NAME"

      - name: Create Release
        if: steps.create_tag.outcome == 'success'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Release ${{ env.TAG_NAME }}"
          body_path: ./release_info.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}

      - name: Upload Asset
        if: steps.create_release.outputs.id != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./exe_packages/recalculation-of-the-smoke-exhaust-fan_${{ github.ref }}.exe
          asset_name: recalculation-of-the-smoke-exhaust-fan_${{ github.ref }}.exe
