name: Release publication

on:
  push:
    branches:
      - main

jobs:
  release-exe-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check changes
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'exe_packages/**'

      - name: Create Tag
        if: steps.check_changes.outputs.src == 'true'
        id: create_tag
        env:
          TAG_TOKEN: ${{ secrets.TAG_TOKEN }}
          VERSION: "v$(date +'%Y.%m.%d')"
        run: |
          git tag "release/v$(date +'%Y.%m.%d')"
          git push --tags https://oauth2:${TAG_TOKEN}@github.com/polnikov/recalculation-smoke-exhaust-fan.git

      - name: Create Release
        if: steps.create_tag.outcome == 'success'
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.VERSION}}
          release_name: "Release ${{env.VERSION}}"
          body_path: ./release_info.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}

      - name: Upload Asset
        if: steps.create_release.outputs.id != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./exe_packages/recalculation-of-the-smoke-exhaust-fan_${{ github.ref }}.exe
          asset_name: recalculation-of-the-smoke-exhaust-fan_${{ github.ref }}.exe
